// server.js
// Metered on-chain data snapshot API.
//
// Flow: agent requests a route -> gets HTTP 402 with price -> pays in USDC on
// Solana -> retries with payment proof -> gets JSON back. No API keys, no
// signup, no dashboard to build. The x402 middleware handles the paywall;
// this file just defines what data each dollar buys and caches upstream
// calls so ten thousand requests don't turn into ten thousand RPC calls.

import express from "express";
import NodeCache from "node-cache";
import rateLimit from "express-rate-limit";
import { buildX402Middleware, routes } from "./x402Middleware.js";
// PATCH (2026-08-08): participant allowlist middleware -- see allowlist.js
// for the full design (off by default, three modes: off/log/enforce).
import { allowlistMiddleware } from "./allowlist.js";
import {
  getEthGasPrice,
  getEthLatestBlock,
  getSolLatestBlock,
  getEthBalance,
  getSolBalance,
  getTokenPrice,
  getPoktServiceDemand,
  getPoktSupplierLandscape,
  getPoktApplicationDemand,
  getPoktTokenomics,
  getPoktThroughputLeaderboard,
  getPoktValidatorSecurity,
  getPoktSupplierTrust,
  getX402SellerTrust,
  getUprockFetch,
  getUprockVerify,
  getBrandVerify,
  getPeaqGasPrice,
  getPeaqLatestBlock,
  getPeaqBalance,
  getPeaqMachineVerification,
  getBscGasPrice,
  getBscLatestBlock,
  getBscBalance,
  getIpGeolocation,
  getPuppeteerScreenshot,
  getHeicToPng,
  getWebSearch,
  getAgentReputation,
  getEthLogs,
  getStablecoinDepeg,
  getYieldAggregation,
  getProtocolHealth,
  getNftCollectionAnalytics,
  getSolTransactionHistory,
  getSanctionsCheck,
  getCurrencyConversion,
  getPuppeteerPdf,
  getImageOcr,
  getSecEdgarFundamentals,
  getWalletSmartMoney,
} from "./dataSources.js";

const app = express();

// Caddy sits in front of this app and terminates TLS, forwarding decrypted
// traffic over the docker network with X-Forwarded-Proto: https. Without
// this line, Express ignores that header and req.protocol falls back to
// "http", which makes the x402 SDK build resource URLs as http://... --
// Bazaar's discovery validator rejects those outright ("resource must start
// with 'https://'"), silently breaking Bazaar listing/updates for every
// route behind this proxy. trust proxy fixes req.protocol at the source
// instead of patching each place that reads it.
//
// Security review, 2026-08-04: this was `true` (trust every hop in
// X-Forwarded-For), which express-rate-limit correctly refused to run
// under -- trusting an unbounded chain of proxies means a client can set
// its own X-Forwarded-For header and present a different "IP" on every
// request, defeating IP-based rate limiting entirely. There is exactly one
// proxy in front of this app (Caddy -- see Caddyfile/docker-compose.yml),
// so `1` (trust exactly one hop) is both correct for this topology and the
// fix the rate limiter needed. If a CDN or a second proxy is ever added in
// front of Caddy, this number needs to go up to match, not back to `true`.
app.set("trust proxy", 1);

// Security review, 2026-08-04: nothing in this app throttled request volume
// before this -- the 402 handshake is free by design (an agent has to be
// able to see the price before paying) and the discovery manifests
// (/.well-known/x402, /openapi.json) are deliberately unmetered, so both
// were pure free-work amplification vectors with zero cost to an attacker.
// A flat per-IP window here doesn't touch the payment logic at all -- it
// just stops any single source from hammering route lookups, manifest
// rebuilds, or 402 responses. Deliberately excludes /health so Docker's own
// healthcheck (which polls frequently, from inside the docker network) can
// never trip it and cause a false "unhealthy" restart loop.
const limiter = rateLimit({
  windowMs: 60 * 1000,
  // BUMPED (2026-08-13): 120/min was tight enough that x402scan's own
  // discovery crawler -- which fans out to every declared route in one pass
  // to read each route's 402 challenge, and re-runs on every manual resync
  // -- was tripping this limit on the tail end of a 20-route catalog and
  // getting a 429 instead of the 402 it needed to register the route.
  // x402scan's own discovery spec calls this exact failure mode out by
  // name: "429 responses are upstream provider limits, not generated by
  // x402scan." A 402 preflight never reaches a real paid data fetch --
  // payment middleware gates everything below this line -- so it's cheap to
  // serve; 600/min (~10/sec/IP) still meaningfully blocks a real scraper
  // while giving a full discovery pass, plus normal traffic in the same
  // window, enough headroom not to self-DoS our own discoverability.
  max: 600,
  standardHeaders: true,
  legacyHeaders: false,
  skip: (req) => req.path === "/health",
  message: { error: "rate limit exceeded, try again shortly" },
});
app.use(limiter);

const PORT = process.env.PORT || 4021;

// Short TTLs: long enough to absorb bursts of agent traffic hitting the same
// route within a few seconds, short enough that the data stays honest.
//
// IMPORTANT (security review, 2026-08-04): this cache sits BELOW the x402
// payment middleware (see app.use(buildX402Middleware()) below) -- every
// request, cache hit or miss, must clear payment verify/settle before this
// function is ever called. A cache hit only skips the upstream RPC/API call;
// it never skips the charge. There is no free-rider path here. Do not read
// "absorbs bursts without re-hitting upstreams" as "absorbs bursts without
// re-charging" -- those are different claims and only the first one is true.
const cache = new NodeCache({ stdTTL: 8, checkperiod: 4 });

async function cached(key, ttl, fn) {
  const hit = cache.get(key);
  if (hit) return hit;
  const value = await fn();
  cache.set(key, value, ttl);
  return value;
}

// Free health check — not metered, so uptime monitors and Bazaar's crawler
// can confirm the service is alive without paying for it.
app.get("/health", (req, res) => res.json({ status: "ok" }));

// PUBLIC_BASE_URL lets the manifest below emit correct absolute resource
// URLs regardless of how the box is reached. Falls back to this domain's
// known public address (Caddy terminates TLS on :8443 in front of this
// container) so the manifest works even if the env var is never set.
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL || "https://organiccryptoyyc.com:8443";

// Substitutes a route's Bazaar-declared example path-param values into its
// Express path template (":name" segments) so /.well-known/x402 advertises
// a real, literally-fetchable "resource" URL instead of the raw route
// pattern.
//
// BUG FIXED (2026-08-12): without this, the manifest advertised e.g.
// "resource": PUBLIC_BASE_URL + "/v1/price/:symbol" verbatim -- any crawler
// that takes that URL at face value and GETs it literally hands Express the
// string ":symbol" as req.params.symbol. That's exactly the
// "Unsupported symbol: :symbol" / "machine id must be a peaq DID ..."
// errors seen in production logs, and very likely why x402scan's discovery
// re-sync was marking several parameterized routes ("skipped") instead of
// registering them -- it couldn't construct a valid call from a manifest
// that only ever offered the unsubstituted template.
function substitutePathParams(path, pathParams) {
  if (!pathParams) return path;
  return path.replace(/:([a-zA-Z0-9_]+)/g, (match, name) =>
    Object.prototype.hasOwnProperty.call(pathParams, name)
      ? encodeURIComponent(String(pathParams[name]))
      : match
  );
}

// "Everything I sell, one link" — the emerging /.well-known/x402 discovery
// convention (see e.g. awesome-x402, x402-discovery-mcp): a single
// unauthenticated, unmetered manifest listing every paid resource on this
// server with its price, network(s), payTo address, and input/output shape,
// so an agent can learn your entire catalog in one GET instead of having to
// already know about Bazaar, know your wallet address, or discover routes by
// trial and error. Built directly from the `routes` export in
// x402Middleware.js -- the same object that drives the live paywall and the
// Bazaar discovery extensions -- so this can never drift out of sync with
// what's actually for sale. Free/unmetered on purpose: an agent needs to be
// able to read the price list before it can decide whether to pay for
// anything, and requiring payment to see the menu defeats the point.
function buildX402Manifest() {
  const resources = Object.entries(routes).map(([routeKey, def]) => {
    const [method, path] = routeKey.split(" ");
    const bazaarInfo = def.extensions?.bazaar?.info;
    const resourcePath = substitutePathParams(path, bazaarInfo?.input?.pathParams);
    return {
      resource: PUBLIC_BASE_URL + resourcePath,
      method,
      type: "http",
      x402Version: 2,
      accepts: def.accepts,
      metadata: {
        description: def.description,
        ...(bazaarInfo?.input ? { input: bazaarInfo.input } : {}),
        ...(bazaarInfo?.output ? { output: bazaarInfo.output } : {}),
      },
    };
  });
  return {
    x402Version: 2,
    name: "organiccryptoyyc.com — Multi-Region Verification & On-Chain Data API",
    description:
      "Real-device, multi-region site verification with screenshot proof, live Pocket Network Shannon " +
      "relay-demand/tokenomics/validator-security data, and Solana/peaq/BSC on-chain snapshots -- " + resources.length + " metered " +
      "x402 routes, priced and settled per call in USDC. Migrating to Acurast decentralized cloud compute for " +
      "censorship-resistant hosting -- stay tuned.",
    resources,
    resourceCount: resources.length,
    // Coinbase's own Bazaar discovery mirrors this same catalog once each
    // route has settled at least one real payment through the CDP
    // facilitator -- useful as a second, independently-hosted place to
    // cross-check this list (and it's queryable by wallet address alone,
    // no knowledge of this domain required).
    alsoDiscoverableVia: {
      bazaarSemanticSearch: "https://api.cdp.coinbase.com/platform/v2/x402/discovery/search",
      bazaarMcpServer: "https://api.cdp.coinbase.com/platform/v2/x402/discovery/mcp",
    },
    lastUpdated: new Date().toISOString(),
  };
}

// Canonical path per the /.well-known/x402 discovery convention, plus a
// `.json` alias since some agent frameworks/crawlers expect an explicit
// extension. Both unmetered -- placed above buildX402Middleware() so
// paymentMiddleware never intercepts them.
app.get(["/.well-known/x402", "/.well-known/x402.json"], (req, res) => {
  res.json(buildX402Manifest());
});

// --- /openapi.json: x402scan's discovery format (separate from Bazaar) -----
// x402scan.com does NOT read /.well-known/x402 or the Bazaar extension -- it
// has its own discovery convention ("Poncho"): an OpenAPI 3.1 document at
// GET /openapi.json where every payable operation carries an `x-payment-info`
// block (price + protocols) alongside a normal `402` response entry. Full
// spec: https://www.x402scan.com/discovery/spec. Confirmed via their own
// discovery probe (2026-08-03) that this origin currently returns "No
// discovery spec found" without this file -- Bazaar/agentic.market listing
// does not imply x402scan listing, they're independent indexes.
//
// Built the same way as buildX402Manifest() above: derived from the single
// `routes` export in x402Middleware.js so it can't drift from what's
// actually for sale. Path/query parameter schemas are read back out of each
// route's Bazaar extension (extensions.bazaar.schema.properties.input...)
// rather than re-declared here, so there's exactly one place (x402Middleware.js)
// where a route's params are described.
//
// Per x402scan's own "Registration gate" rule: publishing this file makes
// the API *discoverable* by their probe, but does NOT register/list it --
// that's a separate, explicit action (POST to their registry) which their
// own docs say should only happen after the deployed origin validates clean
// AND the owner has explicitly approved. This file alone is safe to ship;
// do not wire up automatic registration against x402scan's API without
// asking first.
function toPascalCase(segment) {
  return segment
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function buildOperationId(method, expressPath) {
  const segments = expressPath.split("/").filter((s) => s && s !== "v1");
  const parts = segments.map((s) => (s.startsWith(":") ? "By" + toPascalCase(s.slice(1)) : toPascalCase(s)));
  return method.toLowerCase() + parts.join("");
}

function deriveTag(expressPath) {
  const segments = expressPath.split("/").filter((s) => s && s !== "v1" && !s.startsWith(":"));
  return segments[0] ? toPascalCase(segments[0]) : "General";
}

// Infers a JSON Schema shape from a plain JS example value -- used for the
// 200 response schema so "Input/Output Schema Missing" doesn't fire on
// operations that only declared an `output.example` (not a hand-written
// schema) in their Bazaar discovery extension.
function inferJsonSchema(value) {
  if (value === null || value === undefined) return { type: "string" };
  if (Array.isArray(value)) {
    return { type: "array", items: value.length ? inferJsonSchema(value[0]) : {} };
  }
  const t = typeof value;
  if (t === "number") return { type: Number.isInteger(value) ? "integer" : "number" };
  if (t === "boolean") return { type: "boolean" };
  if (t === "object") {
    const properties = {};
    for (const [k, v] of Object.entries(value)) properties[k] = inferJsonSchema(v);
    return { type: "object", properties };
  }
  return { type: "string" };
}

// BUG FIXED (2026-08-12): added the optional `examples` param. The schema
// half of a route's Bazaar declaration (schema.properties.input.properties.
// pathParams/queryParams) was always being read correctly -- but the
// generated OpenAPI parameter objects never carried an `example`, so any
// consumer building a test invocation from /openapi.json alone (no example
// value to substitute) had nothing better than the literal "{name}" template
// to fall back on. Real example values already exist at
// def.extensions.bazaar.info.input.pathParams / .queryParams (declared via
// declareDiscoveryExtension's own `pathParams`/`input` config) -- this just
// wires them through.
function schemaPropertiesToParameters(schema, location, examples) {
  if (!schema?.properties) return [];
  const required = schema.required || [];
  return Object.entries(schema.properties).map(([name, propSchema]) => ({
    name,
    in: location,
    required: required.includes(name),
    schema: { type: propSchema.type || "string" },
    ...(propSchema.description ? { description: propSchema.description } : {}),
    ...(examples && Object.prototype.hasOwnProperty.call(examples, name)
      ? { example: examples[name] }
      : {}),
  }));
}

function buildOpenApiSpec() {
  const paths = {};
  for (const [routeKey, def] of Object.entries(routes)) {
    const [method, expressPath] = routeKey.split(" ");
    const openApiPath = expressPath.replace(/:([a-zA-Z0-9_]+)/g, "{$1}");
    const bazaarSchema = def.extensions?.bazaar?.schema?.properties?.input?.properties;
    const bazaarInput = def.extensions?.bazaar?.info?.input;
    const outputExample = def.extensions?.bazaar?.info?.output?.example;
    // The Solana accept entry's price is always the "$0.005"-style string
    // (see multiNetworkAccepts() in x402Middleware.js) -- one canonical USD
    // amount per route regardless of how many networks it's payable on.
    const solAccept = def.accepts.find((a) => typeof a.price === "string");
    const amount = solAccept ? solAccept.price.replace("$", "") : "0.00";

    const parameters = [
      ...schemaPropertiesToParameters(bazaarSchema?.pathParams, "path", bazaarInput?.pathParams),
      ...schemaPropertiesToParameters(bazaarSchema?.queryParams, "query", bazaarInput?.queryParams),
    ];

    if (!paths[openApiPath]) paths[openApiPath] = {};
    paths[openApiPath][method.toLowerCase()] = {
      operationId: buildOperationId(method, expressPath),
      summary: def.description.length > 90 ? def.description.slice(0, 87) + "..." : def.description,
      description: def.description,
      tags: [deriveTag(expressPath)],
      ...(parameters.length ? { parameters } : {}),
      "x-payment-info": {
        price: { mode: "fixed", currency: "USD", amount },
        protocols: [{ x402: {} }],
      },
      responses: {
        "200": {
          description: "Successful response",
          content: {
            "application/json": {
              schema: outputExample ? { ...inferJsonSchema(outputExample), example: outputExample } : { type: "object" },
            },
          },
        },
        "402": { description: "Payment Required" },
      },
    };
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "organiccryptoyyc.com — Multi-Region Verification & On-Chain Data API",
      version: "1.0.0",
      description:
        "Real-device, multi-region site verification with screenshot proof, live Pocket Network Shannon " +
        "relay-demand/tokenomics/validator-security data, and Solana/peaq/BSC on-chain snapshots -- " + Object.keys(routes).length +  " metered " +
        "x402 routes, priced and settled per call in USDC. Migrating to Acurast decentralized cloud compute for " +
        "censorship-resistant hosting -- stay tuned.",
      "x-guidance":
        "Every route below is a plain GET request metered with x402 (HTTP 402). Call a route " +
        "unauthenticated first: you'll get a 402 with an `accepts` array listing price/network/payTo " +
        "options (USDC on Solana and, where available, peaq). Pay one of those options and retry the " +
        "same request with payment proof to get JSON back. No API keys, accounts, or subscriptions. " +
        "See /.well-known/x402 for the equivalent Bazaar-style manifest of this same catalog.",
    },
    servers: [{ url: PUBLIC_BASE_URL }],
    paths,
  };
}

// Unmetered, same reasoning as /.well-known/x402 above: an agent needs to be
// able to read this before deciding whether to pay for anything.
app.get("/openapi.json", (req, res) => {
  res.json(buildOpenApiSpec());
});

// Metered routes below this line.
// PATCH (2026-08-08): allowlist gate mounted BEFORE the payment middleware
// -- a blocked caller should never even see a 402 payment prompt for a
// route it isn't allowed to use. Off by default (ALLOWLIST_MODE unset),
// so this is a no-op until explicitly configured -- see allowlist.js.
app.use(allowlistMiddleware());
app.use(buildX402Middleware());

app.get("/v1/eth/gas-price", async (req, res, next) => {
  try {
    res.json(await cached("eth:gas", 5, getEthGasPrice));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/eth/latest-block", async (req, res, next) => {
  try {
    res.json(await cached("eth:block", 8, getEthLatestBlock));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/sol/latest-block", async (req, res, next) => {
  try {
    res.json(await cached("sol:slot", 3, getSolLatestBlock));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/price/:symbol", async (req, res, next) => {
  try {
    const { symbol } = req.params;
    res.json(await cached(`price:${symbol}`, 15, () => getTokenPrice(symbol)));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/wallet/balance/:chain/:address", async (req, res, next) => {
  try {
    const { chain, address } = req.params;
    const key = `bal:${chain}:${address}`;
    const fn =
      chain === "eth"
        ? () => getEthBalance(address)
        : chain === "sol"
        ? () => getSolBalance(address)
        : chain === "peaq"
        ? () => getPeaqBalance(address)
        : chain === "bsc"
        ? () => getBscBalance(address)
        : null;
    if (!fn) return res.status(400).json({ error: "chain must be 'eth', 'sol', 'peaq', or 'bsc'" });
    res.json(await cached(key, 6, fn));
  } catch (err) {
    next(err);
  }
});

// IP geolocation. Long TTL (3600s) relative to the RPC routes above --
// unlike gas price or block height, which chain/country an IP resolves to
// almost never changes minute to minute, so a tight cache would just burn
// FreeIPAPI's rate limit for no fresher data.
const IPV4_RE = /^(\d{1,3}\.){3}\d{1,3}$/;
const IPV6_RE = /^[0-9a-fA-F:]+$/;
app.get("/v1/geo/ip/:ip", async (req, res, next) => {
  try {
    const { ip } = req.params;
    const isV4 = IPV4_RE.test(ip) && ip.split(".").every((oct) => Number(oct) <= 255);
    const isV6 = ip.includes(":") && IPV6_RE.test(ip);
    if (!isV4 && !isV6) return res.status(400).json({ error: "ip must be a valid IPv4 or IPv6 address" });
    res.json(await cached(`geo:ip:${ip}`, 3600, () => getIpGeolocation(ip)));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/peaq/gas-price", async (req, res, next) => {
  try {
    res.json(await cached("peaq:gas", 5, getPeaqGasPrice));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/peaq/latest-block", async (req, res, next) => {
  try {
    res.json(await cached("peaq:block", 8, getPeaqLatestBlock));
  } catch (err) {
    next(err);
  }
});

// BNB Smart Chain (BSC). Same TTL rationale as the eth/peaq gas + block
// routes above -- sellable today via the existing Solana/peaq payment rails
// even though BSC itself isn't wired up as a payment network yet (see
// x402Middleware.js).
app.get("/v1/bsc/gas-price", async (req, res, next) => {
  try {
    res.json(await cached("bsc:gas", 5, getBscGasPrice));
  } catch (err) {
    next(err);
  }
});

app.get("/v1/bsc/latest-block", async (req, res, next) => {
  try {
    res.json(await cached("bsc:block", 8, getBscLatestBlock));
  } catch (err) {
    next(err);
  }
});

// peaq machine trust/verification lookup (peaqOS MCR API). Longer TTL (300s)
// than the RPC routes above -- upstream's own MCR score cache defaults to
// 3600s, so polling faster than a few minutes just burns our request budget
// against peaq's 90 req/min-per-IP rate limit for no fresher data.
app.get("/v1/peaq/machine-verify/:idOrAddress", async (req, res, next) => {
  try {
    const { idOrAddress } = req.params;
    res.json(await cached(`peaq:verify:${idOrAddress}`, 300, () => getPeaqMachineVerification(idOrAddress)));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon relay-demand ranking. Longer TTL (60s) than the RPC routes
// above — the underlying EMA only moves meaningfully on the order of tens of
// seconds to minutes, so a tighter cache would just burn indexer load for no
// fresher data.
app.get("/v1/pokt/service-demand", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:demand:${limit || 10}`, 60, () => getPoktServiceDemand(limit)));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon supplier landscape. Same 60s TTL rationale as service-demand
// above -- staked-actor counts move on the order of sessions, not seconds.
app.get("/v1/pokt/suppliers", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:suppliers:${limit || 10}`, 60, () => getPoktSupplierLandscape(limit)));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon application (demand-side) stake feed.
app.get("/v1/pokt/applications", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:applications:${limit || 10}`, 60, () => getPoktApplicationDemand(limit)));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon tokenomics / settlement split. Longer TTL (300s) -- these are
// governance params that change by proposal, not by the block, per
// pocket-engineering's caching guidance (cache ~1hr max, this is more
// conservative than that ceiling).
app.get("/v1/pokt/tokenomics", async (req, res, next) => {
  try {
    res.json(await cached("pokt:tokenomics", 300, getPoktTokenomics));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon throughput-by-service leaderboard (all-time cumulative
// claimed volume). 120s TTL -- this one costs an N+1-aliased GraphQL query
// per cache miss, so it's worth not hammering the indexer every request.
app.get("/v1/pokt/throughput", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:throughput:${limit || 10}`, 120, () => getPoktThroughputLeaderboard(limit)));
  } catch (err) {
    next(err);
  }
});

// POKT Shannon validator security / decentralization feed. 300s TTL -- the
// bonded validator set changes rarely (unstaking has multi-session unbonding
// periods), so this doesn't need to be fresh to the minute.
app.get("/v1/pokt/validators", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:validators:${limit || 10}`, 300, () => getPoktValidatorSecurity(limit)));
  } catch (err) {
    next(err);
  }
});

// UpRock real-device fetch. Longer TTL (180s) than everything else on
// purpose: each crawl job costs real UpRock credits, so a repeat request for
// the same URL inside the cache window is free margin instead of a repeat
// charge against your UpRock balance.
app.get("/v1/uprock/fetch", async (req, res, next) => {
  try {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: "url query param is required" });
    res.json(await cached(`uprock:${url}`, 180, () => getUprockFetch(url)));
  } catch (err) {
    next(err);
  }
});

// UpRock Verify (multi-region sweep). PATCH (2026-08-08). 300s TTL -- each
// call is a multi-region sweep (real UpRock-billed jobs, plural), so a
// cache hit here saves real credit spend, same rationale as /v1/uprock/fetch
// above but a longer window since a domain's verification status doesn't
// need to be fresher than a few minutes for most callers.
app.get("/v1/uprock/verify/:domain", async (req, res, next) => {
  try {
    const { domain } = req.params;
    const regions =
      typeof req.query.regions === "string"
        ? req.query.regions.split(",").map((r) => r.trim().toUpperCase()).filter(Boolean)
        : undefined;
    const cacheKey = `uprock:verify:${domain}:${regions ? regions.join(",") : "default"}`;
    res.json(await cached(cacheKey, 300, () => getUprockVerify(domain, { regions })));
  } catch (err) {
    next(err);
  }
});

  // pokt_supplier_trust (composite): live on-chain stake status (Pocketdex) + a
  // bounded, SSRF-hardened reachability probe of the supplier's own advertised
  // RPC endpoints. $0.05/call -- for gateways, indexers, and node monitoring
  // tools deciding whether to route relays to a given supplier.
  // 300s cache: stake status and endpoint reachability don't need to be fresher
  // than a few minutes for most callers, and this avoids re-probing live IPs
  // on every request.
  app.get("/v1/pokt/supplier-trust/:operatorId", async (req, res, next) => {
        try {
                const { operatorId } = req.params;
                res.json(await cached(`pokt:supplier-trust:${operatorId}`, 300, () => getPoktSupplierTrust(operatorId)));
        } catch (err) {
                next(err);
        }
  });

// x402_seller_trust (composite): live Bazaar usage/social proof + a live 402
// reachability probe of the seller's own advertised resources + the
// seller's own manifest quality + hosting legitimacy (DNS/IP intel),
// rolled into a single 0-100 trust score for an x402 SELLER (not a POKT
// supplier -- see /v1/pokt/supplier-trust for that). $0.27/call.
// 600s cache: Bazaar's own 30-day usage numbers don't need fresher than
// 10-minute granularity, and this avoids re-probing a stranger's server on
// every request.
app.get("/v1/x402/seller-trust/:encodedUrl", async (req, res, next) => {
  try {
    // NOTE (2026-08-15): switched from a `?url=` query param to a URL-encoded
    // path segment after live-testing conclusively showed CDP's facilitator
    // rejects ANY payment whose resource URL contains a query string --
    // confirmed by bisecting price down to an exact match with the
    // known-working /v1/brand-verify route (same $0.23, same atomic amount)
    // and by re-testing with the query value itself properly percent-encoded
    // -- both still failed identically ('paymentPayload' is invalid: must
    // match one of [x402V2Pay...). Removing the query string entirely (this
    // route is the only paid route on this server that REQUIRED one) is the
    // next thing to isolate. Caller must encodeURIComponent() the full
    // seller base URL as the path segment.
    let url;
    try {
      url = decodeURIComponent(req.params.encodedUrl);
    } catch {
      return res.status(400).json({ error: "encodedUrl path segment must be percent-encoded" });
    }
    if (!url) return res.status(400).json({ error: "encodedUrl path segment is required" });
    res.json(await cached(`x402-seller-trust:${url}`, 600, () => getX402SellerTrust(url)));
  } catch (err) {
    next(err);
  }
});

// brand_verify (composite): domain-to-IP resolution + multi-region UpRock Verify
// (screenshots/Core Web Vitals) + IP intelligence (geo/proxy detection), rolled into
// a single 0-100 trust score. $0.23/call -- trust & safety, compliance, brand
// protection, anti-fraud, and "is this site live and hosted where expected" checks.
// 300s cache, same rationale as /v1/uprock/verify: each call is a real multi-region
// UpRock sweep plus an IP intelligence lookup, so a cache hit here saves real spend.
app.get("/v1/brand-verify/:domain", async (req, res, next) => {
  try {
    const { domain } = req.params;
    const regions =
      typeof req.query.regions === "string"
        ? req.query.regions.split(",").map((r) => r.trim().toUpperCase()).filter(Boolean)
        : undefined;
    const cacheKey = `brand-verify:${domain}:${regions ? regions.join(",") : "default"}`;
    res.json(await cached(cacheKey, 300, () => getBrandVerify(domain, { regions })));
  } catch (err) {
    next(err);
  }
});

// Headless-Chrome screenshot render (Puppeteer, via the puppeteer-render
// service -- see dataSources.js/puppeteer-render.js for the architecture).
// $0.03/call. 30s cache -- much shorter than this file's other caches
// (which mostly guard real upstream credit spend): a rendered page's visual
// state can change quickly, and there's no per-call credit cost here to
// protect, just repeat compute -- 30s still absorbs a tight burst of
// requests for the same URL without serving a stale screenshot for long.
app.get("/v1/render/screenshot", async (req, res, next) => {
  try {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: "url query param is required" });
    res.json(await cached(`render:screenshot:${url}`, 30, () => getPuppeteerScreenshot(url)));
  } catch (err) {
    next(err);
  }
});

// HEIC to PNG conversion. $0.005/call, pure compute -- no second container
// needed the way render/screenshot needed one. 60s cache: converting the
// same source URL twice inside that window is free margin instead of a
// repeat decode.
app.get("/v1/convert/heic-to-png", async (req, res, next) => {
  try {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: "url query param is required" });
    res.json(await cached(`convert:heic-to-png:${url}`, 60, () => getHeicToPng(url)));
  } catch (err) {
    next(err);
  }
});

// Web search (self-hosted SearXNG). $0.008/call. 30s cache -- search
// results can shift quickly, and there's no per-call credit cost to
// protect here, just repeat compute against our own searxng instance --
// same rationale as render/screenshot's 30s window above.
app.get("/v1/search/web", async (req, res, next) => {
  try {
    const { q, limit } = req.query;
    if (!q) return res.status(400).json({ error: "q query param is required" });
    res.json(await cached(`search:web:${q}:${limit || ""}`, 30, () => getWebSearch(q, { limit })));
  } catch (err) {
    next(err);
  }
});

// ERC-8004 agent reputation lookup. $0.03/call. 120s cache -- on-chain
// feedback doesn't need to be fresher than a couple minutes for most
// callers, and this avoids re-running the same handful of eth_calls on
// every request for a popular agentId.
app.get("/v1/agent/reputation/:agentId", async (req, res, next) => {
  try {
    const { agentId } = req.params;
    const chain = typeof req.query.chain === "string" ? req.query.chain : undefined;
    const cacheKey = `agent:reputation:${chain || "eth"}:${agentId}`;
    res.json(await cached(cacheKey, 120, () => getAgentReputation(agentId, { chain })));
  } catch (err) {
    next(err);
  }
});

// Tier A historical/indexed chain data (2026-08-16). $0.012/call. 15s cache
// -- roughly one ETH block's worth of staleness tolerance, matching the
// eth:block route's own 8s TTL in spirit (a bit looser here since this is a
// range query, not a single latest-block read).
app.get("/v1/eth/logs", async (req, res, next) => {
  try {
    const { address, topic0, blocks, decimals, tokenUsdPrice, minUsd } = req.query;
    if (!address) return res.status(400).json({ error: "address query param is required" });
    const cacheKey = `eth:logs:${address}:${topic0 || ""}:${blocks || ""}:${decimals || ""}:${tokenUsdPrice || ""}:${minUsd || ""}`;
    res.json(await cached(cacheKey, 15, () => getEthLogs(address, { topic0, blocks, decimals, tokenUsdPrice, minUsd })));
  } catch (err) {
    next(err);
  }
});

// Stablecoin depeg monitor (2026-08-22). $0.01/call. 60s cache -- price
// checks don't need eth/logs-level freshness.
app.get("/v1/stablecoin/depeg-check", async (req, res, next) => {
  try {
    const { symbols, thresholdPct } = req.query;
    const cacheKey = `stablecoin:depeg:${symbols || "all"}:${thresholdPct || ""}`;
    res.json(await cached(cacheKey, 60, () => getStablecoinDepeg({ symbols, thresholdPct })));
  } catch (err) {
    next(err);
  }
});

// DeFi/staking yield aggregation (2026-08-22). $0.01-0.02/call (network-dependent
// via multiNetworkAccepts). 10min cache -- DefiLlama's own pool snapshot doesn't
// refresh faster than that, so polling more often than this just re-serves stale data.
app.get("/v1/defi/yields", async (req, res, next) => {
  try {
    const { chain, project, symbol, stablecoinOnly, minTvlUsd, sortBy, limit, includeOutliers } = req.query;
    const cacheKey = `defi:yields:${chain || ""}:${project || ""}:${symbol || ""}:${stablecoinOnly || ""}:${minTvlUsd || ""}:${sortBy || ""}:${limit || ""}:${includeOutliers || ""}`;
    res.json(await cached(cacheKey, 600, () => getYieldAggregation({ chain, project, symbol, stablecoinOnly, minTvlUsd, sortBy, limit, includeOutliers })));
  } catch (err) {
    next(err);
  }
});

// Protocol/chain health composite (2026-08-22). $0.02/call (network-dependent
// via multiNetworkAccepts). 10min cache -- matches defi/yields' TTL since it
// shares the same DefiLlama upstream freshness.
app.get("/v1/protocol/health", async (req, res, next) => {
  try {
    const { protocol, chain } = req.query;
    if (!protocol && !chain) return res.status(400).json({ error: "protocol or chain query param is required" });
    const cacheKey = `protocol:health:${protocol || ""}:${chain || ""}`;
    res.json(await cached(cacheKey, 600, () => getProtocolHealth({ protocol, chain })));
  } catch (err) {
    next(err);
  }
});

// NFT collection analytics (2026-08-22). $0.015/call (network-dependent via
// multiNetworkAccepts). 5min cache -- floor/volume data moves faster than
// TVL-style metrics, so this is shorter than defi/yields' and
// protocol/health's 10min TTL.
app.get("/v1/nft/analytics", async (req, res, next) => {
  try {
    const { collection, contractAddress, chain } = req.query;
    if (!collection && !(contractAddress && chain)) {
      return res.status(400).json({ error: "collection or contractAddress+chain query param is required" });
    }
    const cacheKey = `nft:analytics:${collection || ""}:${contractAddress || ""}:${chain || ""}`;
    res.json(await cached(cacheKey, 300, () => getNftCollectionAnalytics({ collection, contractAddress, chain })));
  } catch (err) {
    next(err);
  }
});

// Tier A historical/indexed chain data (2026-08-16). $0.01/call. 20s cache --
// polling a "most recent N transactions" view more often than that rarely
// surfaces anything new.
app.get("/v1/sol/history/:address", async (req, res, next) => {
  try {
    const { address } = req.params;
    const { limit } = req.query;
    const cacheKey = `sol:history:${address}:${limit || ""}`;
    res.json(await cached(cacheKey, 20, () => getSolTransactionHistory(address, { limit })));
  } catch (err) {
    next(err);
  }
});

// OFAC sanctions screening (2026-08-16). $0.015/call. The underlying SDN
// address list is cached in-process by dataSources.js itself (6h TTL, see
// loadOfacLists()) since it's shared across every address lookup rather
// than being per-request cacheable the way the cached() calls above are --
// once the list is loaded, a per-address answer is a free Set.has() and
// isn't worth caching again on top of that.
app.get("/v1/compliance/sanctions-check/:address", async (req, res, next) => {
  try {
    const { address } = req.params;
    const { chain } = req.query;
    res.json(await getSanctionsCheck(address, { chain }));
  } catch (err) {
    next(err);
  }
});


// Currency conversion (ECB reference rates via Frankfurter, free/keyless
// upstream -- 2026-08-22). $0.01/call. 3600s cache -- ECB rates only
// update once daily, so an hour-long cache costs no real accuracy.
app.get("/v1/currency/convert", async (req, res, next) => {
  try {
    const { from, to, amount } = req.query;
    if (!from || !to) return res.status(400).json({ error: "from and to query params are required" });
    const cacheKey = `currency:convert:${String(from).toUpperCase()}:${String(to).toUpperCase()}:${amount || 1}`;
    res.json(await cached(cacheKey, 3600, () => getCurrencyConversion(from, to, amount)));
  } catch (err) {
    next(err);
  }
});

// Webpage-to-PDF render, via the puppeteer-render service (2026-08-22).
// $0.01/call. 30s cache -- same rationale as render/screenshot below.
app.get("/v1/render/pdf", async (req, res, next) => {
  try {
    const { url, format, landscape } = req.query;
    if (!url) return res.status(400).json({ error: "url query param is required" });
    const cacheKey = `render:pdf:${url}:${format || "Letter"}:${landscape ? "landscape" : "portrait"}`;
    res.json(await cached(cacheKey, 30, () => getPuppeteerPdf(url, { format, landscape: landscape === "true" })));
  } catch (err) {
    next(err);
  }
});

// Image OCR (Tesseract, via the puppeteer-render service -- 2026-08-22).
// $0.01/call. 60s cache -- same source image OCR'd twice inside that window
// is free margin instead of a repeat Tesseract pass.
app.get("/v1/image/ocr", async (req, res, next) => {
  try {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: "url query param is required" });
    res.json(await cached(`image:ocr:${url}`, 60, () => getImageOcr(url)));
  } catch (err) {
    next(err);
  }
});


// SEC EDGAR company fundamentals (2026-08-23). $0.02/call. 6h cache -- SEC
// filing data only changes a few times a year per company (quarterly 10-Qs,
// annual 10-K), so caching this long trades effectively zero freshness for a
// large cut in load against the SEC shared, rate-limited (10 req/s) API.
app.get("/v1/sec/fundamentals/:ticker", async (req, res, next) => {
  try {
    const { ticker } = req.params;
    res.json(
      await cached(`sec:fundamentals:${String(ticker).toUpperCase()}`, 21600, () =>
        getSecEdgarFundamentals(ticker)
      )
    );
  } catch (err) {
    next(err);
  }
});


// Wallet smart-money scoring (2026-08-23). $0.02/call. 5-minute cache -- much
// shorter than the sanctions/SEC caches since balance and tx-count change in
// real time and this route is explicitly about current activity.
app.get("/v1/wallet/smart-money/:chain/:address", async (req, res, next) => {
  try {
    const { chain, address } = req.params;
    res.json(
      await cached(`wallet:smart-money:${chain}:${address}`, 300, () =>
        getWalletSmartMoney(chain, address)
      )
    );
  } catch (err) {
    next(err);
  }
});

// PATCH (2026-08-19): pay.sh internal proxy routes.
//
// pay.sh (https://pay.sh) runs its own payment gateway (`pay gate api`) on
// its own infrastructure: it does the 402 handshake itself, using its own
// rails, then in `routing: proxy` mode forwards the already-paid request to
// an upstream URL. It is NOT built to sit in front of an API that already
// does its own x402 gating -- pointed at a public /v1/* route here, this
// app's own buildX402Middleware() would just 402 the (already-paid) request
// again, since it has no way to know pay.sh already collected payment.
//
// Fix: these /internal/paysh/* routes are a second, unauthenticated-by-x402
// front door onto the exact same data functions, deliberately NOT registered
// in x402Middleware.js's `routes` map (buildX402Middleware() only gates
// paths listed there, so anything else -- these included -- passes straight
// through Express untouched by the payment layer). Gated instead by a
// shared secret only pay.sh's provider.yml knows and injects
// (`X-Internal-Key`, via provider.yml's `routing.auth` block) -- fails
// closed if PAYSH_INTERNAL_KEY isn't set, so a misconfigured deploy 503s
// instead of silently giving this catalog away for free. Cache keys are
// shared with the matching public route (same `cached()` calls) so a
// pay.sh-routed call and a direct call for the same resource don't double
// the upstream load.
//
// Only the 10 routes with no existing pay.sh-catalog equivalent are exposed
// here (see provider.yml) -- the commodity RPC routes (gas price, latest
// block, wallet balance) aren't, since Quicknode already covers that lane on
// pay.sh far more comprehensively.
function requirePayshKey(req, res, next) {
  const expected = process.env.PAYSH_INTERNAL_KEY;
  if (!expected) {
    return res.status(503).json({ error: "PAYSH_INTERNAL_KEY is not configured" });
  }
  if (req.headers["x-internal-key"] !== expected) {
    return res.status(401).json({ error: "invalid or missing X-Internal-Key" });
  }
  next();
}
app.use("/internal/paysh", requirePayshKey);

app.get("/internal/paysh/v1/pokt/service-demand", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:demand:${limit || 10}`, 60, () => getPoktServiceDemand(limit)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/pokt/suppliers", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:suppliers:${limit || 10}`, 60, () => getPoktSupplierLandscape(limit)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/pokt/applications", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:applications:${limit || 10}`, 60, () => getPoktApplicationDemand(limit)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/pokt/tokenomics", async (req, res, next) => {
  try {
    res.json(await cached("pokt:tokenomics", 300, getPoktTokenomics));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/pokt/throughput", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:throughput:${limit || 10}`, 120, () => getPoktThroughputLeaderboard(limit)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/pokt/validators", async (req, res, next) => {
  try {
    const limit = req.query.limit;
    res.json(await cached(`pokt:validators:${limit || 10}`, 300, () => getPoktValidatorSecurity(limit)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/peaq/machine-verify/:idOrAddress", async (req, res, next) => {
  try {
    const { idOrAddress } = req.params;
    res.json(await cached(`peaq:verify:${idOrAddress}`, 300, () => getPeaqMachineVerification(idOrAddress)));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/compliance/sanctions-check/:address", async (req, res, next) => {
  try {
    const { address } = req.params;
    const { chain } = req.query;
    res.json(await getSanctionsCheck(address, { chain }));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/brand-verify/:domain", async (req, res, next) => {
  try {
    const { domain } = req.params;
    const regions =
      typeof req.query.regions === "string"
        ? req.query.regions.split(",").map((r) => r.trim().toUpperCase()).filter(Boolean)
        : undefined;
    const cacheKey = `brand-verify:${domain}:${regions ? regions.join(",") : "default"}`;
    res.json(await cached(cacheKey, 300, () => getBrandVerify(domain, { regions })));
  } catch (err) {
    next(err);
  }
});

app.get("/internal/paysh/v1/x402/seller-trust/:encodedUrl", async (req, res, next) => {
  try {
    let url;
    try {
      url = decodeURIComponent(req.params.encodedUrl);
    } catch {
      return res.status(400).json({ error: "encodedUrl path segment must be percent-encoded" });
    }
    if (!url) return res.status(400).json({ error: "encodedUrl path segment is required" });
    res.json(await cached(`x402-seller-trust:${url}`, 600, () => getX402SellerTrust(url)));
  } catch (err) {
    next(err);
  }
});

// Centralized error handler — never leak stack traces to paying callers.
app.use((err, req, res, _next) => {
  console.error(err);
  res.status(502).json({ error: "upstream data source failed", detail: err.message });
});

app.listen(PORT, () => {
  console.log(`Snapshot API listening on :${PORT}`);
});
